kriasoft/node-sqlite

- src/index.js
Hey, 
please excuse the not-so-perfect title of this PR.
In the current versions of node (I tested 5.4.x and 5.5.x) the new [es6 enhanced object literal syntax](https://github.com/lukehoban/es6features#enhanced-object-literals) does work if the object has the name 'get'. One should avoid the new syntax when dealing with an object named 'get'.
I didn't find any node in the specs about get being an reserved keyword, so maybe this is an node bug?
To reproduce this behavior:
```js
const foo = 1
const bar = 2
const get = 3
// works as expected:
const test1 = {foo, bar}
// works as expected too:
const test3 = {get: get, foo, bar}
// does not work
const test2 = {get, foo, bar}
/*
const test2 = {get, foo, bar}
^
SyntaxError: Unexpected token ,
*/
```
> Export fix for strange enhanced object literal syntax behavior please excuse the not-so-perfect title of this PR.

- package.json
- src/Database.js
- src/Statement.js
- src/utils.js
- test/spec.js
In various places, rest parameter syntax (e.g. `...params`) was used to
represent the parameters to an SQL statement. The problem with this
approach is that it would not allow named parameters to be used, because
in order to use named parameters, an object must be passed as the params
to the driver method, but passing an object as the first parameter would
end up being wrapped in an array, and the driver method would treat the
object as a single parameter.
This commit replaces the uses of rest parameter syntax with a check
whether there is exactly one parameter whose type is 'object'. If so,
that object is used as the params to the driver method. Otherwise, an
appropriate slice of the `arguments` array-like object is used as the
params to the driver method.
> Support using named parameters

- package.json
For some reason Yarn keeps using 3.1.6
> Upgrade sqlite3 to latest

- src/Database.js
On a partially or fully up-to-date db, calling `db.migrate()` would result in duplicate execution of migrations because `lastMigrationId` [retrieved the first migration id due to the DESC ordering of the dbMigrations query](https://github.com/kriasoft/node-sqlite/blob/master/src/Database.js#L197).
This throws an error in the migration script if it isn't idempotent, or the following error in the migrations table when it tries to insert the pre-existing migration with the same id:
```
{ Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: migrations.id
at Error (native) errno: 19, code: 'SQLITE_CONSTRAINT' }
```
My fix flips the order of the `dbMigrations` query so the highest migration is at the end.
> Fix duplicate migration application when db.migrate() is run multiple times

- src/Database.js
Just had an app blow up in production because I exceeded 10 schemas on a db that's never been migrated before. 😨
Before: 
```
> [ { id: 7, name: 'rtg', filename: '007-rtg.sql' },
{ id: 1,
name: 'initial-schema',
filename: '001-initial-schema.sql' },
{ id: 8, name: 'betive', filename: '008-betive.sql' },
{ id: 3, name: 'enforce-keys', filename: '003-enforce-keys.sql' },
{ id: 2,
name: 'first-provider',
filename: '002-first-provider.sql' },
{ id: 4, name: 'dup-accounts', filename: '004-dup-accounts.sql' },
{ id: 5, name: 'program-url', filename: '005-program-url.sql' },
{ id: 6,
name: 'gambling-stats',
filename: '006-gambling-stats.sql' },
{ id: 9, name: 'radium', filename: '009-radium.sql' },
{ id: 10, name: 'programs', filename: '010-programs.sql' },
{ id: 11, name: 'rival', filename: …
```
> bug: Fix sorting of schemas

- src/main.d.ts
It would be nice to be able to provide the type system with the information about domain objects using generics:
```
interface SomeDomainObject {
id: number;
name: string;
}
const obj = await db.get<SomeDomainObject>('SELECT id, name FROM some_domain_objects')
```
> Make ambient declarations more useful for type inference

- migrations/003-test-cert.sql
- src/Database.js
- test/spec.js
Fixes https://github.com/kriasoft/node-sqlite/issues/27
> Fix migration bug where using -- as an actual string value gets lost

- README.md
- src/main.js
- test/spec.js
Implements https://github.com/kriasoft/node-sqlite/issues/29
> Add ability to use custom sqlite3 driver

- src/Database.js
I happened to have a comment starting with `-- Downloaded` being considered as a separator… this commit ensures only the word “down” counts as a separator when it starts a comment.
> Match only “down” as separator

- src/main.d.ts
As of TypeScript 2.6.1, ambient type files (`*.d.ts`) can no longer contain any executable code. Stated another way -- these files may only contain type information that disappears completely during the TS -> JS compilation process.
More info on this change here: https://github.com/Microsoft/TypeScript/issues/17991
> Remove executable code from ambient type file

- src/Database.js
- src/main.d.ts
Without exposing the whole sqlite3 driver, this small change allows registration of `trace` and `profile` hooks.
More info: https://github.com/mapbox/node-sqlite3/wiki/Debugging
> Expose sqlite3 debugging hooks

- README.md
`sqlite.open('./database.sqlite', { cached: true })`
was written twice as
`sqlite.open('./database.sqlite', { cached: true }))`
> Fix syntax error in examples

- src/Database.js
- src/main.d.ts
Without exposing the whole sqlite3 driver, this small change allows configure method.
more info: https://github.com/mapbox/node-sqlite3/wiki/API#databaseconfigureoption-value
> expose sqlite3 configure method

- CHANGELOG.md
- package.json
There's a prototype pollution vulnerability in `sqlite@3.1.13` introduced through an obsolete version of `node-pre-gyp` more info on which can be found here: https://snyk.io/test/npm/sqlite3/3.1.13
Updating to `sqlite@4.0.0` fixes this vulnerability: https://snyk.io/test/npm/sqlite3/4.0.0.
As far as I've checked, `v4.0.0` doesn't seem to introduce any breaking change that requires any changes to `node-sqlite`. So, this PR shouldn't break any thing.
*I've bumped the version & updated the changelog as well, please verify them as well.*
> Update sqlite3 to v4.0.0

- package.json
- yarn.lock
This should fix #70 
sqlite3@4.0.0 uses a version of node-pre-gyp that requires needle to fetch pre-compiled sqlite3 binaries. Needle didn't play nice with people behind proxies, so the change has been reverted, causing a bump to sqlite3 to 4.0.2
My project uses sqlite and we can't upgrade to 2.9.2 because of this specific dependency. Merging this and creating a 2.9.3 version would be nice and allow us to upgrade to sqlite3@4.x.x
Thanks in advance
> Updated dependency to sqlite3@4.0.2 refs #70

- README.md
ASP.NET starter link url actually links to the react starter kit. Fixed that.
> Correct ASP.NET Core Starter Link Url

- src/main.js.flow
Resolves the issue of `Database` and `Statement` objects being retrievable (via this library's api), but not possible to type annotate (on local code).
> Export class types for flow

- src/Statement.ts
- src/__tests__/Sqlite3.test.ts
- src/__tests__/index.test.ts
- src/index.ts
- src/interfaces.ts
- src/utils/__tests__/migrate.test.ts
- src/utils/migrate.ts
- tsconfig.json
Hello!  Thanks for the update on this last night.  I've had another look and think I've found the root of the particular problem I was having.  This project previously used allowSyntheticDefaultImports to allow modules without a default export defined to be used as though they have one.  Any consuming packages would then also need this TypeScript compiler configuration change; it's a workaround for some more exotic uses of module imports and isn't intended for general use (https://github.com/microsoft/TypeScript/issues/10895#issuecomment-246926958).
In this PR I've disabled allowSyntheticDefaultImports and adjusted module imports where there's been an impact.  Thanks!
> Use non-default imports rather than synthetic default imports

- src/vendor-typings/sqlite3/index.d.ts
This PR fixes the function definition.
Implicit "any" in definition file can cause compilation error in external project.
> Fix typescript defs for sqlite3 loadExtension()

- src/vendor-typings/sqlite3/index.d.ts
Triple slash references need to be the [in first statements of a typescript source file to be recognized](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html), currently this one is ignored (at least in ts 3.8.3) and so the event type is not included in compilation (unless included elsewhere)
Also resolves https://github.com/haxiomic/dts2hx/issues/15
> Fix invalid triple slash reference

- README.md
Shields.io badges are being loaded using HTTP, causing mixed-content errors in [the NPM page](https://www.npmjs.com/package/sqlite).
> Use HTTPS in README badges

- README.md
- package-lock.json
@akc42 pointed out that the docs for `db.run` says it returns `lastId` when it should be `lastID`.
Fixes https://github.com/kriasoft/node-sqlite/issues/119
> Update readme for inserting rows

- README.md
- docs/classes/_src_database_.database.md
- docs/classes/_src_statement_.statement.md
- docs/interfaces/_src_interfaces_.imigrate.migrationfile.md
- docs/interfaces/_src_interfaces_.imigrate.migrationparams.md
- docs/interfaces/_src_interfaces_.isqlite.config.md
- docs/interfaces/_src_interfaces_.isqlite.runresult.md
- docs/interfaces/_src_interfaces_.isqlite.sqlobj.md
- docs/modules/_src_index_.md
- docs/modules/_src_interfaces_.isqlite.md
- docs/modules/_src_utils_migrate_.md
- docs/modules/_src_utils_strings_.md
- src/Database.ts
- src/interfaces.ts
The `filename` property is back to being required, but empty strings are valid values for the purpose of using an anonymous disk-based database.
Values of `undefined` or `null` for `filename` will throw.
Addresses https://github.com/kriasoft/node-sqlite/issues/123
> Revert filename optional; update filename checks instead

- src/interfaces.ts
- src/utils/__tests__/migrate.test.ts
- src/utils/migrate.ts
I like the migrations feature, but I'm working on a bundled JavaScript project where I want to have control over how the migrations data is read off the disk. It would be great if the data could be supplied directly to the migrate function from memory, without involving the filesystem.
> Let migrations be read manually

- package.json
- src/Database.ts
- src/Statement.ts
- src/__tests__/Sqlite3.test.ts
- src/utils/__tests__/format-error.test.ts
- src/utils/format-error.ts
Addresses https://github.com/kriasoft/node-sqlite/issues/156
This ensures that errors thrown from the sqlite driver now
have stack traces and are of an `Error` type.
Thanks to @fresheneesz for initial troubleshooting and initial
code to help fix the issue.
This is a minor level version update as to not break implementations
that may handle errors in their own way prior to this fix.
> Have native sqlite errors contain stack traces

- package.json
in TS 4.7+ node16/next module mode, if library contains`exports` section, TypeScript compiler will only reads `exports.**.types` field.
more info: https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/
> Support TS 4.7+ node16/next module mode

- package-lock.json
- package.json
- src/Database.ts
As `exec` is not a part of `Statement` (https://github.com/TryGhost/node-sqlite3/blob/master/src/statement.cc#L17), but a part of `Database` itself (https://github.com/TryGhost/node-sqlite3/blob/master/src/database.cc#L21), it does not support `params` binding. So, we should not expose `params` to the `exec` public interface here. Also, this corresponds to `node-sqlite3` API docs (https://github.com/TryGhost/node-sqlite3/wiki/API#execsql--callback).
> Remove `params` parameter from `exec` function

- package-lock.json
- package.json
- src/vendor-typings/sqlite3/index.d.ts
This replaces the types in `vendor-typings/sqlite3/index.d.ts` with the one from the `sqlite3` project and not the definitelyTyped ones.
Addresses https://github.com/kriasoft/node-sqlite/issues/175
> Update vendor typings to use sqlite3
